spring.application.name=gestodered

# Error handling configuration
server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true

spring.mongodb.uri=mongodb://localhost:27017/gestor_bd
spring.data.mongodb.auto-index-creation=true

gestordered.ryu-api-url=http://127.0.0.1:8080
gestordered.mininet-api-url=http://127.0.0.1:8081
gestordered.network-api-key=gestordered-tfg-network-api-key-2026


#server.port=8082
