spring.application.name=gestodered

# Error handling configuration
server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true

spring.mongodb.uri=mongodb://admin:admin@localhost:27017/gestor_bd?authSource=gestor_bd
spring.data.mongodb.auto-index-creation=true

gestordered.network-api-key=gestordered-tfg-network-api-key-2026


server.port=8082
